### ISSUE TITLE
obs_collection details

### ISSUE THREAD

**Issue by Bonnarel** [ivoa/HighEnergyDataNote#2]
In 6.2.1 the draft reads 
> "obs_collection could contain many details : obs_type (calib, science),
obs_mode (subarray configuration), pointing_mode, tracking_mode,
event_type, event_cuts, analysis_type. . ."

This has been extensively discussed in the french sub-club. But as the text already proposes several items can they be considered of potential part of the HeI extension or is that another table ? In the latter case obs_collection can be used as a foreign key in the second table. Is that what is needed ? 

tracking_mode exists already in ObsLocTap and is called tracking_type

**Comment by mservillat** [comment]
changed to tracking_type, though this section will probably evolve again
