### ISSUE TITLE
t_min, t_max subsection should be called t_gti

### ISSUE THREAD

**Issue by Bonnarel** [ivoa/HighEnergyDataNote#3]
In section 6.2.3 the "t_min, t_max" item has a wrong denomination.*

6.2.3 title is called "metadata addition required".  

So it should not contain any ObsCore standard item. When reading the text of this item we realize it should be called t_gti instead , because this is actually the new term which is, proposed to describe a set of good time intervals.

**Comment by mservillat** [comment]
indeed, changed
