### ISSUE TITLE
ObsCore section : dataproduct_subtype is not mandatory 

### ISSUE THREAD

**Issue by loumir** [ivoa/HighEnergyDataNote#36]
proposal : 
a- remove the first bullet on data product subtype from the list . 

b- add a short caveat : 
dataproduct_subtype is optional and free text. 
it's content  may vary between various experiments . 

c- the serialization data format ( OGIP, VODF, etc ) is handled in Obscore in Access.format . 
we must check that the related MIME types are allowed in ObsCore and if not add them .

**Comment by loumir** [comment]
the file  format used in high energy data are not covered yet by Obscore 1.1 
OGIP, VODF, etc should be added to the accepted format , or instead a vocabulary can be defined to identify all ObsCore accepted formats .

**Comment by mservillat** [comment]
I updated the text to resolve those issues, I hope this is fine

**Comment by mservillat** [comment]
commits where not properly integrated, now they are : #41
