### ISSUE TITLE
Comments on the version of April, 4th, 2024

### ISSUE THREAD

**Issue by bkhelifi** [ivoa/HighEnergyDataNote#6]
Dear all,
Here are some comments and propositions of modification to be discussed or included directly:
[VOHE-Note-draft.pdf](https://github.com/ivoa/HighEnergyDataNote/files/14873194/VOHE-Note-draft.pdf)

**Comment by mservillat** [comment]
Thanks for the comments, the document has been updated accordingly, sometimes adding or rephrasing some parts
